service: tasks-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
    enviroments:
      SECRET: d198cc52488409c78f2d139781e299f6cd0e83cafb26f1c0658f8c15de5df872
      DB_USER: 'tasksadmin123'
      DB_PASS: 'tasksadmin123'
      DB_NAME: 'tasks'
      DB_HOST: 'database-1.cxgucek0wzwn.us-east-1.rds.amazonaws.com'
      DB_PORT: 3306
      DB_DLCT: 'mysql'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
